# Generated by Django 4.1 on 2023-10-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
